// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAlertPolicy(arg1:main.AlertPolicy):Promise<void>;

export function AddAlertRule(arg1:main.AlertRule):Promise<void>;

export function AddDevice(arg1:main.Device):Promise<void>;

export function AddDeviceGroup(arg1:main.DeviceGroup):Promise<void>;

export function AddFieldMappingDoc(arg1:main.FieldMappingDoc):Promise<void>;

export function AddFilterPolicy(arg1:main.FilterPolicy):Promise<void>;

export function AddOutputTemplate(arg1:main.OutputTemplate):Promise<void>;

export function AddParseTemplate(arg1:main.ParseTemplate):Promise<void>;

export function AddRobot(arg1:main.DingTalkRobot):Promise<main.DingTalkRobot>;

export function AddTemplate(arg1:main.Template):Promise<void>;

export function CleanupAllLogs():Promise<void>;

export function CleanupLogs(arg1:number):Promise<void>;

export function CleanupUnmatchedLogs(arg1:number):Promise<void>;

export function DeleteAlertPolicy(arg1:number):Promise<void>;

export function DeleteAlertRule(arg1:number):Promise<void>;

export function DeleteAlertRulesByRobotID(arg1:number):Promise<void>;

export function DeleteDevice(arg1:number):Promise<void>;

export function DeleteDeviceGroup(arg1:number):Promise<void>;

export function DeleteFieldMappingDoc(arg1:number):Promise<void>;

export function DeleteFilterPolicy(arg1:number):Promise<void>;

export function DeleteOutputTemplate(arg1:number):Promise<void>;

export function DeleteParseTemplate(arg1:number):Promise<void>;

export function DeleteRobot(arg1:number):Promise<void>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function ExportFilterPolicies(arg1:Array<number>):Promise<string>;

export function ExportParseTemplates(arg1:Array<number>):Promise<string>;

export function ExportTemplates(arg1:Array<number>):Promise<Array<main.Template>>;

export function FormatSyslogMessage(arg1:string):Promise<Record<string, string>>;

export function GetAlertPolicies():Promise<Array<main.AlertPolicy>>;

export function GetAlertPolicy(arg1:number):Promise<main.AlertPolicy>;

export function GetAlertRecords(arg1:number,arg2:number):Promise<Array<main.AlertRecord>|number>;

export function GetAlertRule(arg1:number):Promise<main.AlertRule>;

export function GetAlertRules(arg1:number):Promise<Array<main.AlertRule>>;

export function GetAppVersion():Promise<string>;

export function GetAvailableStatsFields(arg1:number):Promise<Array<main.StatsField>>;

export function GetConfig():Promise<main.SystemConfig>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetDevice(arg1:number):Promise<main.Device>;

export function GetDeviceGroup(arg1:number):Promise<main.DeviceGroup>;

export function GetDeviceGroups():Promise<Array<main.DeviceGroup>>;

export function GetDevices():Promise<Array<main.Device>>;

export function GetFieldMappingDoc(arg1:number):Promise<main.FieldMappingDoc>;

export function GetFieldMappingDocByDeviceType(arg1:string):Promise<main.FieldMappingDoc>;

export function GetFieldMappingDocByName(arg1:string):Promise<main.FieldMappingDoc>;

export function GetFieldMappingDocs():Promise<Array<main.FieldMappingDoc>>;

export function GetFieldStats(arg1:main.FieldStatsRequest):Promise<main.FieldStatsResult>;

export function GetFilterPolicies():Promise<Array<main.FilterPolicy>>;

export function GetFilterPolicy(arg1:number):Promise<main.FilterPolicy>;

export function GetImportDirectory():Promise<string>;

export function GetLocalIP():Promise<string>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetLogTraceInfo(arg1:number):Promise<main.LogTraceInfo>;

export function GetLogs(arg1:main.LogQueryParams):Promise<main.LogQueryResult>;

export function GetOutputTemplate(arg1:number):Promise<main.OutputTemplate>;

export function GetOutputTemplates():Promise<Array<main.OutputTemplate>>;

export function GetParseTemplate(arg1:number):Promise<main.ParseTemplate>;

export function GetParseTemplates():Promise<Array<main.ParseTemplate>>;

export function GetPlatformInfo():Promise<string>;

export function GetPresetTemplates():Promise<Array<main.PresetTemplate>>;

export function GetRobot(arg1:number):Promise<main.DingTalkRobot>;

export function GetRobots():Promise<Array<main.DingTalkRobot>>;

export function GetServiceStatus():Promise<Record<string, any>>;

export function GetSystemStats():Promise<main.SystemStats>;

export function GetTemplate(arg1:number):Promise<main.Template>;

export function GetTemplates():Promise<Array<main.Template>>;

export function GetUnmatchedLogsCount():Promise<number>;

export function ImportFilterPolicies(arg1:string):Promise<main.ImportResult>;

export function ImportParseTemplates(arg1:string):Promise<main.ImportResult>;

export function ImportTemplates(arg1:Array<main.Template>):Promise<void>;

export function ReadImportFile(arg1:string):Promise<string>;

export function SaveConfig(arg1:main.SystemConfig):Promise<void>;

export function SaveExportedFile(arg1:string,arg2:string):Promise<string>;

export function ScanImportFiles():Promise<Array<string>>;

export function SendTestSyslog(arg1:main.TestSyslogRequest):Promise<main.TestSyslogResult>;

export function StartSyslogService(arg1:number,arg2:string):Promise<void>;

export function StopSyslogService():Promise<void>;

export function TestDingTalkWebhook(arg1:string,arg2:string):Promise<string>;

export function TestEmail(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function TestFeishuWebhook(arg1:string,arg2:string):Promise<string>;

export function TestParseTemplate(arg1:main.ParseTestRequest):Promise<main.ParseTestResult>;

export function TestRegex(arg1:string,arg2:string):Promise<Record<string, any>>;

export function TestSyslogForward(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function TestWeworkWebhook(arg1:string,arg2:string):Promise<string>;

export function UpdateAlertPolicy(arg1:main.AlertPolicy):Promise<void>;

export function UpdateAlertRule(arg1:main.AlertRule):Promise<void>;

export function UpdateDevice(arg1:main.Device):Promise<void>;

export function UpdateDeviceGroup(arg1:main.DeviceGroup):Promise<void>;

export function UpdateFieldMappingDoc(arg1:main.FieldMappingDoc):Promise<void>;

export function UpdateFilterPolicy(arg1:main.FilterPolicy):Promise<void>;

export function UpdateOutputTemplate(arg1:main.OutputTemplate):Promise<void>;

export function UpdateParseTemplate(arg1:main.ParseTemplate):Promise<void>;

export function UpdateRobot(arg1:main.DingTalkRobot):Promise<void>;

export function UpdateStats(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function UpdateTemplate(arg1:main.Template):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;
