// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAlertPolicy(arg1) {
  return window['go']['main']['App']['AddAlertPolicy'](arg1);
}

export function AddAlertRule(arg1) {
  return window['go']['main']['App']['AddAlertRule'](arg1);
}

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function AddDeviceGroup(arg1) {
  return window['go']['main']['App']['AddDeviceGroup'](arg1);
}

export function AddFieldMappingDoc(arg1) {
  return window['go']['main']['App']['AddFieldMappingDoc'](arg1);
}

export function AddFilterPolicy(arg1) {
  return window['go']['main']['App']['AddFilterPolicy'](arg1);
}

export function AddOutputTemplate(arg1) {
  return window['go']['main']['App']['AddOutputTemplate'](arg1);
}

export function AddParseTemplate(arg1) {
  return window['go']['main']['App']['AddParseTemplate'](arg1);
}

export function AddRobot(arg1) {
  return window['go']['main']['App']['AddRobot'](arg1);
}

export function AddTemplate(arg1) {
  return window['go']['main']['App']['AddTemplate'](arg1);
}

export function CleanupAllLogs() {
  return window['go']['main']['App']['CleanupAllLogs']();
}

export function CleanupLogs(arg1) {
  return window['go']['main']['App']['CleanupLogs'](arg1);
}

export function CleanupUnmatchedLogs(arg1) {
  return window['go']['main']['App']['CleanupUnmatchedLogs'](arg1);
}

export function DeleteAlertPolicy(arg1) {
  return window['go']['main']['App']['DeleteAlertPolicy'](arg1);
}

export function DeleteAlertRule(arg1) {
  return window['go']['main']['App']['DeleteAlertRule'](arg1);
}

export function DeleteAlertRulesByRobotID(arg1) {
  return window['go']['main']['App']['DeleteAlertRulesByRobotID'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DeleteDeviceGroup(arg1) {
  return window['go']['main']['App']['DeleteDeviceGroup'](arg1);
}

export function DeleteFieldMappingDoc(arg1) {
  return window['go']['main']['App']['DeleteFieldMappingDoc'](arg1);
}

export function DeleteFilterPolicy(arg1) {
  return window['go']['main']['App']['DeleteFilterPolicy'](arg1);
}

export function DeleteOutputTemplate(arg1) {
  return window['go']['main']['App']['DeleteOutputTemplate'](arg1);
}

export function DeleteParseTemplate(arg1) {
  return window['go']['main']['App']['DeleteParseTemplate'](arg1);
}

export function DeleteRobot(arg1) {
  return window['go']['main']['App']['DeleteRobot'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExportFilterPolicies(arg1) {
  return window['go']['main']['App']['ExportFilterPolicies'](arg1);
}

export function ExportParseTemplates(arg1) {
  return window['go']['main']['App']['ExportParseTemplates'](arg1);
}

export function ExportTemplates(arg1) {
  return window['go']['main']['App']['ExportTemplates'](arg1);
}

export function FormatSyslogMessage(arg1) {
  return window['go']['main']['App']['FormatSyslogMessage'](arg1);
}

export function GetAlertPolicies() {
  return window['go']['main']['App']['GetAlertPolicies']();
}

export function GetAlertPolicy(arg1) {
  return window['go']['main']['App']['GetAlertPolicy'](arg1);
}

export function GetAlertRecords(arg1, arg2) {
  return window['go']['main']['App']['GetAlertRecords'](arg1, arg2);
}

export function GetAlertRule(arg1) {
  return window['go']['main']['App']['GetAlertRule'](arg1);
}

export function GetAlertRules(arg1) {
  return window['go']['main']['App']['GetAlertRules'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAvailableStatsFields(arg1) {
  return window['go']['main']['App']['GetAvailableStatsFields'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDevice(arg1) {
  return window['go']['main']['App']['GetDevice'](arg1);
}

export function GetDeviceGroup(arg1) {
  return window['go']['main']['App']['GetDeviceGroup'](arg1);
}

export function GetDeviceGroups() {
  return window['go']['main']['App']['GetDeviceGroups']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetFieldMappingDoc(arg1) {
  return window['go']['main']['App']['GetFieldMappingDoc'](arg1);
}

export function GetFieldMappingDocByDeviceType(arg1) {
  return window['go']['main']['App']['GetFieldMappingDocByDeviceType'](arg1);
}

export function GetFieldMappingDocByName(arg1) {
  return window['go']['main']['App']['GetFieldMappingDocByName'](arg1);
}

export function GetFieldMappingDocs() {
  return window['go']['main']['App']['GetFieldMappingDocs']();
}

export function GetFieldStats(arg1) {
  return window['go']['main']['App']['GetFieldStats'](arg1);
}

export function GetFilterPolicies() {
  return window['go']['main']['App']['GetFilterPolicies']();
}

export function GetFilterPolicy(arg1) {
  return window['go']['main']['App']['GetFilterPolicy'](arg1);
}

export function GetImportDirectory() {
  return window['go']['main']['App']['GetImportDirectory']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetLogTraceInfo(arg1) {
  return window['go']['main']['App']['GetLogTraceInfo'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetOutputTemplate(arg1) {
  return window['go']['main']['App']['GetOutputTemplate'](arg1);
}

export function GetOutputTemplates() {
  return window['go']['main']['App']['GetOutputTemplates']();
}

export function GetParseTemplate(arg1) {
  return window['go']['main']['App']['GetParseTemplate'](arg1);
}

export function GetParseTemplates() {
  return window['go']['main']['App']['GetParseTemplates']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetPresetTemplates() {
  return window['go']['main']['App']['GetPresetTemplates']();
}

export function GetRobot(arg1) {
  return window['go']['main']['App']['GetRobot'](arg1);
}

export function GetRobots() {
  return window['go']['main']['App']['GetRobots']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetUnmatchedLogsCount() {
  return window['go']['main']['App']['GetUnmatchedLogsCount']();
}

export function ImportFilterPolicies(arg1) {
  return window['go']['main']['App']['ImportFilterPolicies'](arg1);
}

export function ImportParseTemplates(arg1) {
  return window['go']['main']['App']['ImportParseTemplates'](arg1);
}

export function ImportTemplates(arg1) {
  return window['go']['main']['App']['ImportTemplates'](arg1);
}

export function ReadImportFile(arg1) {
  return window['go']['main']['App']['ReadImportFile'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveExportedFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExportedFile'](arg1, arg2);
}

export function ScanImportFiles() {
  return window['go']['main']['App']['ScanImportFiles']();
}

export function SendTestSyslog(arg1) {
  return window['go']['main']['App']['SendTestSyslog'](arg1);
}

export function StartSyslogService(arg1, arg2) {
  return window['go']['main']['App']['StartSyslogService'](arg1, arg2);
}

export function StopSyslogService() {
  return window['go']['main']['App']['StopSyslogService']();
}

export function TestDingTalkWebhook(arg1, arg2) {
  return window['go']['main']['App']['TestDingTalkWebhook'](arg1, arg2);
}

export function TestEmail(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TestEmail'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestFeishuWebhook(arg1, arg2) {
  return window['go']['main']['App']['TestFeishuWebhook'](arg1, arg2);
}

export function TestParseTemplate(arg1) {
  return window['go']['main']['App']['TestParseTemplate'](arg1);
}

export function TestRegex(arg1, arg2) {
  return window['go']['main']['App']['TestRegex'](arg1, arg2);
}

export function TestSyslogForward(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestSyslogForward'](arg1, arg2, arg3, arg4);
}

export function TestWeworkWebhook(arg1, arg2) {
  return window['go']['main']['App']['TestWeworkWebhook'](arg1, arg2);
}

export function UpdateAlertPolicy(arg1) {
  return window['go']['main']['App']['UpdateAlertPolicy'](arg1);
}

export function UpdateAlertRule(arg1) {
  return window['go']['main']['App']['UpdateAlertRule'](arg1);
}

export function UpdateDevice(arg1) {
  return window['go']['main']['App']['UpdateDevice'](arg1);
}

export function UpdateDeviceGroup(arg1) {
  return window['go']['main']['App']['UpdateDeviceGroup'](arg1);
}

export function UpdateFieldMappingDoc(arg1) {
  return window['go']['main']['App']['UpdateFieldMappingDoc'](arg1);
}

export function UpdateFilterPolicy(arg1) {
  return window['go']['main']['App']['UpdateFilterPolicy'](arg1);
}

export function UpdateOutputTemplate(arg1) {
  return window['go']['main']['App']['UpdateOutputTemplate'](arg1);
}

export function UpdateParseTemplate(arg1) {
  return window['go']['main']['App']['UpdateParseTemplate'](arg1);
}

export function UpdateRobot(arg1) {
  return window['go']['main']['App']['UpdateRobot'](arg1);
}

export function UpdateStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStats'](arg1, arg2, arg3);
}

export function UpdateTemplate(arg1) {
  return window['go']['main']['App']['UpdateTemplate'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}
